export const bookingFormInputs = [
  {
    id: 1,
    label: "Booking Type",
    type: "text",
    name: "bookingType",
    options: ["First Time", "Retake", "Resit"],
    inputType: "select",
  },
  {
    id: 2,
    label: "Retirement Scheme Name",
    type: "text",
    name: "retirementSchemeName",
    options: [
      "A I C KIJABE MEDICA",
      "A I C KIJABE PRINTING",
      "AIC LITENI CATTAGE",
    ],
    inputType: "select",
  },
  {
    id: 3,
    label: "Full Name",
    type: "text",
    name: "fullName",
    value: "fullName",
    inputType: "input",
  },
  {
    id: 4,
    label: "Scheme Position",
    type: "text",
    name: "schemePosition",
    value: "schemePosition",
    inputType: "input",
  },
  {
    id: 5,
    label: "ID Number",
    type: "text",
    name: "idNumber",
    value: "idNumber",
    inputType: "input",
  },

  {
    id: 6,
    label: "Email",
    type: "email",
    name: "email",
    value: "email",
    inputType: "input",
  },
  {
    id: 7,
    label: "Telephone",
    type: "text",
    name: "telephone",
    value: "telephone",
    inputType: "input",
  },
  {
    id: 8,
    label: "Physical Address",
    type: "text",
    name: "physicalAddress",
    value: "physicalAddress",
    inputType: "input",
  },
  {
    id: 9,
    label: "Employer Name",
    type: "text",
    name: "employerName",
    value: "employerName",
    inputType: "input",
  },
  {
    id: 10,
    label: "Retirement Scheme Name",
    type: "text",
    name: "originCountry",
    options: ["Kenya", "Uganda", "Tanzania", "Others"],
    inputType: "select",
  },
  {
    id: 11,
    label: "Training Venue",
    type: "text",
    name: "trainingVenue",
    options: ["INHOUSE", "Kisumu", "Nairobi", "Mombasa"],
    inputType: "select",
  },
  {
    id: 12,
    label: "Course Date",
    type: "date",
    name: "courseDate",
    inputType: "input",
  },
  {
    id: 13,
    label: "Experience (years)",
    type: "number",
    name: "experience",
    value: "experience",
    inputType: "input",
  },
  {
    id: 14,
    label: "Position",
    type: "text",
    name: "position",
    value: "position",
    inputType: "input",
  },
  {
    id: 15,
    label: "Payment Mode",
    type: "text",
    name: "paymentMode",
    options: ["Cheque", "Cash", "Electronic Funds Transfer"],
    inputType: "select",
  },
  {
    id: 16,
    label: "Additional Requirements",
    type: "text",
    name: "additionalRequirements",
    value: "additionalRequirements",
    inputType: "input",
  },
  {
    id: 17,
    label: "External Scheme Admin",
    type: "text",
    name: "externalSchemeAdmin",
    value: "externalSchemeAdmin",
    inputType: "input",
  },
  {
    id: 18,
    label: "Disability Status",
    name: "disabilityStatus",
    value: "disabilityStatus",
    options: ["Disabled", "Not Disabled"],
    inputType: "select",
  },
];
