const Constant = {
  ACTION: {
    STORE: "store/",
    DEFAULT: "DEFAULT/",
    DASHBOARD: "/dashboard",
    CHECK_AUTH_STATE: "account/isloggedin",
    CATEGORY: "category/",
    CONTENT: "content/",
    CSRFTOKEN: "/GetCsrfToken",
    BOOKING: "booking/",
    PAGES: "pages/",
    PRODUCT_GROUP: "products/group/",
    PRODUCT: "product/",
    PRODUCTS: "products/",
    CART: "cart/",
    CARTS: "cart",
    PRICE: "price/",
    CUSTOMER: "customer/",
    LOGIN: "login/",
    CUSTOMERS: "customers/",
    MANUFACTURERS: "manufacturers/",
    VARIANTS: "variants/",
    CONFIG: "config/",
    COUNTRY: "country/",
    ZONES: "zones/",
    AUTH: "auth/",
    ONBOARDING: "/onboarding",
    PROFILE: "profile",
    SHIPPING: "shipping",
    TOTAL: "total/",
    NEWSLETTER: "newsletter/",
    PASSWORD_RESET: "/AccountSettings/PasswordReset",
    REGISTER: "register",
    CHECKOUT: "checkout",
    USER_PROFILE_EDIT: "AccountSettings/UserProfileEdit",
    CONTACT: "contact/",
    ORDERS: "orders/",
    ADDRESS: "address",
    RESET: "reset/",
    REQUEST: "request/",
    SEARCH: "search/",
    AUTOCOMPLETE: "autocomplete/",
    BOXES: "boxes/",
    BANNER_TEXT: "bannerText/",
    IMAGES: "images/",
    HEADER_MESSAGE: "headerMessage/",
    AGREEMENT: "agreement/",
    PROMO: "promo/",
    PAYMENT_LINK: `/payment/cashfree/capture`,
    ORDER_HISTORY: "history",
    TRACKING: "/tracking/",
    USER: "/GetUser",
    USER_WALLET: "/auth/wallet/user",
    WALLET_HISTORY: "/auth/wallet/user/history",
    WALLET: "/wallet",
  },
  ROUTE: {
    BOOKING: "bookings",
    ORDER: "P2P/orders",
  },
};

export default Constant;
